#Requires -Version 5.1
<#
  Copy built frontend and backend to a simple folder layout (default C:\webapps\jims).
  No IIS, no web.config — just www\ + backend\ + run-api.ps1.

  Usage:
    .\scripts\deploy-webapps.ps1
    .\scripts\deploy-webapps.ps1 -TargetRoot 'D:\apps\jims'
    .\scripts\deploy-webapps.ps1 -ViteBase '/jims/'
#>
param(
    [string]$TargetRoot = 'C:\webapps\jims',
    [string]$ViteBase = '/'
)

$ErrorActionPreference = 'Stop'

$RepoRoot = Split-Path $PSScriptRoot -Parent
if (-not (Test-Path (Join-Path $RepoRoot 'package.json'))) {
    throw "Cannot find repo root (expected package.json next to scripts/)."
}

$wwwRoot = Join-Path $TargetRoot 'www'
$backendDest = Join-Path $TargetRoot 'backend'
$readmeSrc = Join-Path $RepoRoot 'deploy\webapps\README.txt'

function Write-RunApiScript {
    param([string]$Path)
    @'
# Generated by scripts/deploy-webapps.ps1
$ErrorActionPreference = 'Stop'
Set-Location $PSScriptRoot
Set-Location .\backend
python -m uvicorn app.main:app --host 127.0.0.1 --port 8001
'@ | Set-Content -Path $Path -Encoding UTF8
}

Write-Host "Repository: $RepoRoot" -ForegroundColor Cyan
Write-Host "Deploy target: $TargetRoot" -ForegroundColor Cyan

if ($ViteBase -ne '/') {
    Push-Location $RepoRoot
    try {
        npm run build -- --base=$ViteBase
        if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
    } finally {
        Pop-Location
    }
} else {
    Push-Location $RepoRoot
    try {
        npm run build
        if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
    } finally {
        Pop-Location
    }
}

$dist = Join-Path $RepoRoot 'dist'
if (-not (Test-Path (Join-Path $dist 'index.html'))) {
    throw "dist/index.html not found after build."
}

New-Item -ItemType Directory -Path $wwwRoot -Force | Out-Null
Get-ChildItem -Path $wwwRoot -Force -ErrorAction SilentlyContinue | Remove-Item -Recurse -Force
Copy-Item -Path (Join-Path $dist '*') -Destination $wwwRoot -Recurse -Force

New-Item -ItemType Directory -Path $backendDest -Force | Out-Null
$backendSrc = Join-Path $RepoRoot 'backend'
robocopy $backendSrc $backendDest /E /NFL /NDL /NJH /NJS /nc /ns /np `
    /XD __pycache__ .pytest_cache .venv venv .eggs tests `
    /XF jims.db *.pyc *.pyo | Out-Null
$rc = $LASTEXITCODE
if ($rc -ge 8) {
    throw "robocopy backend failed (exit $rc)"
}

$envExample = Join-Path $backendSrc '.env.example'
$envDest = Join-Path $backendDest '.env'
if ((-not (Test-Path $envDest)) -and (Test-Path $envExample)) {
    Copy-Item $envExample $envDest
    Write-Host "Created backend\.env from .env.example - edit SECRET_KEY and DATABASE_URL." -ForegroundColor Yellow
}

if (Test-Path $readmeSrc) {
    Copy-Item $readmeSrc (Join-Path $TargetRoot 'README.txt') -Force
}

Write-RunApiScript -Path (Join-Path $TargetRoot 'run-api.ps1')

Write-Host ''
Write-Host 'Done.' -ForegroundColor Green
Write-Host "  Static files: $wwwRoot"
Write-Host "  Backend:      $backendDest"
Write-Host "  Start API:    $TargetRoot\run-api.ps1"
Write-Host "  See:          $TargetRoot\README.txt"
